/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EthDistributorInterface extends ethers.utils.Interface {
  functions: {
    "contributionLimit()": FunctionFragment;
    "contributionsPerAddress(address)": FunctionFragment;
    "contributors(uint256)": FunctionFragment;
    "distributeEther()": FunctionFragment;
    "hasContributed(address)": FunctionFragment;
    "maximumContributors()": FunctionFragment;
    "minimumContribution()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateContributionLimit(uint256)": FunctionFragment;
    "withdrawAllAddressEther()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "contributionLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributionsPerAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "contributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeEther",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasContributed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "maximumContributors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumContribution",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContributionLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllAddressEther",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "contributionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributionsPerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasContributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maximumContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContributionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllAddressEther",
    data: BytesLike
  ): Result;

  events: {
    "Contribution(address,uint256)": EventFragment;
    "Distribution(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Withdrawal(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Contribution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Distribution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawal"): EventFragment;
}

export type ContributionEvent = TypedEvent<
  [string, BigNumber] & { _from: string; _value: BigNumber }
>;

export type DistributionEvent = TypedEvent<
  [string, BigNumber] & { _to: string; _amount: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type WithdrawalEvent = TypedEvent<
  [string, BigNumber] & { _to: string; _value: BigNumber }
>;

export class EthDistributor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EthDistributorInterface;

  functions: {
    contributionLimit(overrides?: CallOverrides): Promise<[BigNumber]>;

    contributionsPerAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    contributors(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    distributeEther(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasContributed(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    maximumContributors(overrides?: CallOverrides): Promise<[BigNumber]>;

    minimumContribution(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateContributionLimit(
      _newContributionLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawAllAddressEther(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  contributionLimit(overrides?: CallOverrides): Promise<BigNumber>;

  contributionsPerAddress(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  contributors(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  distributeEther(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasContributed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  maximumContributors(overrides?: CallOverrides): Promise<BigNumber>;

  minimumContribution(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateContributionLimit(
    _newContributionLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawAllAddressEther(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    contributionLimit(overrides?: CallOverrides): Promise<BigNumber>;

    contributionsPerAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contributors(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    distributeEther(overrides?: CallOverrides): Promise<void>;

    hasContributed(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    maximumContributors(overrides?: CallOverrides): Promise<BigNumber>;

    minimumContribution(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateContributionLimit(
      _newContributionLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAllAddressEther(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Contribution(address,uint256)"(
      _from?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _from: string; _value: BigNumber }
    >;

    Contribution(
      _from?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _from: string; _value: BigNumber }
    >;

    "Distribution(address,uint256)"(
      _to?: null,
      _amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _to: string; _amount: BigNumber }
    >;

    Distribution(
      _to?: null,
      _amount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _to: string; _amount: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Withdrawal(address,uint256)"(
      _to?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _to: string; _value: BigNumber }
    >;

    Withdrawal(
      _to?: null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { _to: string; _value: BigNumber }
    >;
  };

  estimateGas: {
    contributionLimit(overrides?: CallOverrides): Promise<BigNumber>;

    contributionsPerAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contributors(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    distributeEther(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasContributed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    maximumContributors(overrides?: CallOverrides): Promise<BigNumber>;

    minimumContribution(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateContributionLimit(
      _newContributionLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawAllAddressEther(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    contributionLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contributionsPerAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contributors(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    distributeEther(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasContributed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maximumContributors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumContribution(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateContributionLimit(
      _newContributionLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAllAddressEther(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
